version: '3.8'

services:
  # Frontend (interface web estática servida pelo Nginx)
  painel:
    build:
      context: ./painel
      dockerfile: Dockerfile
    image: nmalls-painel:latest
    container_name: nmalls-painel
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - app-network

  # Backend (API Node.js)
  api:
    build:
      context: ./painel
      dockerfile: Dockerfile.api
    image: nmalls-api:latest
    container_name: nmalls-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 