version: '3.8'

services:
  painel:
    build:
      context: ./painel
      dockerfile: Dockerfile
    container_name: nmalls-painel
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SUPABASE_URL=sua_url_do_supabase
      - SUPABASE_KEY=sua_chave_do_supabase
      - JWT_SECRET=seu_segredo_para_jwt
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./painel:/app
      - /app/node_modules 