version: '3.8'

services:
  painel:
    build:
      context: ./painel
      dockerfile: Dockerfile
    image: nmalls-painel:latest
    container_name: nmalls-painel
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    volumes:
      - ./painel:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 